name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm clang libclang-dev

    - name: Set LIBCLANG_PATH
      run: |
        echo "LIBCLANG_PATH=$(dirname $(find /usr -name 'libclang-*.so' | head -n 1))" >> $GITHUB_ENV

    - name: Set LLVM_CONFIG_PATH
      run: |
        echo "LLVM_CONFIG_PATH=$(which llvm-config)" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose